### ISSUE TITLE
Error while plotting EF 

### ISSUE THREAD

**Issue by jorgdeboer** [robertmartin8/PyPortfolioOpt#332] opened 2021-05-10 11:10 UTC
**Describe the bug**
While trying to plot the Efficient Frontier, the following error occurs:

TypeError: can't pickle osqp.OSQP_results objects

**Expected behavior**
Expected to get a plot of the effecient frontier.

**Code sample**

```python
import pandas as pd
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import plotting
from pypfopt import expected_returns
import matplotlib.pyplot as plt


# Read in price data
df = pd.read_csv("stock_prices.csv", parse_dates=True, index_col="date")

# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
weights = ef.max_sharpe()
ef.portfolio_performance(verbose=True)


fig, ax = plt.subplots()
plotting.plot_efficient_frontier(ef, ax=ax, show_assets=False)
```

**Operating system, python version, PyPortfolioOpt version**
Windows 10, python 3.7, PyPortfolioOpt 1.4.1

**Comment by robertmartin8** [comment] 2021-05-10 15:32
Hi @jorgdeboer,

Thanks for raising this! The problem is that you have called `ef.max_sharpe()` before plotting. If you remove this, it should work (let me know if not!)

I should probably add a try/catch or something to ensure that a more sensible error message is raised, but his issue is closely related to quite a deep architectural problem (#307).

Best,
Robert

**Comment by jorgdeboer** [comment] 2021-05-10 15:51
Thanks for the quick reply!

However, while removing the ef.sharpe_ratio(), im getting a new error:

Process finished with exit code -1073740940 (0xC0000374).

That is however probably a pycharm/python issue, so let me dive into that.

Thanks,

Jorg

**Comment by robertmartin8** [comment] 2021-05-10 19:09
@jorgdeboer quite a scary-sounding error 😨 

If you'd like to test code (to see whether it's a problem with PyPortfolioOpt or your environment), a good way of doing it is via [binder](https://mybinder.org/v2/gh/robertmartin8/pyportfolioopt/master/?filepath=cookbook). You can even upload your own data (but it disappears when the server shuts down). When people raise bugs, the first thing I always do is try to replicate it in binder. 

Best,
Robert

**Comment by robertmartin8** [comment] 2021-05-17 14:50
I'm closing for now as I suspect it's an installation/environment thing. But please feel free to reopen if needed!

**Closed by robertmartin8** 2021-05-17 14:50 UTC
Labels: question
