### ISSUE TITLE
ModuleNotFoundError: No module named 'pulp'

### ISSUE THREAD

**Issue by akitxu** [robertmartin8/PyPortfolioOpt#62] opened 2020-01-07 10:54 UTC
Dear Robert
As you can see in the attached image, the import of modules returns the error mentioned in the query title.
![GestionValores](https://user-images.githubusercontent.com/40218417/71890301-41d16300-3144-11ea-8031-aaf25cd31f10.PNG)
Perhaps modifications to the API have affected some package names. `What should be the new names in the API, of "DiscreteAllocation or get_latest_prices"?
I will appreciate your help. Best regards

**Comment by akitxu** [comment] 2020-01-07 11:39
The problem is that We have to install a new module called "pulp"
Thank you

**Comment by schneiderfelipe** [comment] 2020-01-07 15:32
[The need for pulp is explained in the docs](https://pyportfolioopt.readthedocs.io/en/latest/Postprocessing.html#integer-programming), although it's not clear whether this is an optional dependency. Should this be included in the docs @robertmartin8?

**Comment by robertmartin8** [comment] 2020-01-07 22:40
@felipeschneider I'm not sure what the most pythonic solution is. It's
certainly not a core dependency in the same way that pandas is, but of
course it's needed for some of the methods in the discrete allocation model.

I could take off pulp from requirements, but what is the expected behaviour
when people try to run a discrete allocator? Presumably there will be a
ModuleNotFound error - do you think users can figure out that they must pip
install it?

Robert

**Comment by schneiderfelipe** [comment] 2020-01-08 00:08
> @FelipeSchneider I'm not sure what the most pythonic solution is. It's certainly not a core dependency in the same way that pandas is, but of course it's needed for some of the methods in the discrete allocation model.

I agree. I think [a solution like this one](https://github.com/cclib/cclib/blob/da10a949bf66512ffb38a56e97de2dba6d9afc38/cclib/bridge/cclib2psi4.py#L12) is interesting.

Basically, fail silently at import, but throw an error as soon as the functionality is required. What do you think?

**Comment by akitxu** [comment] 2020-01-08 19:50
However, I need the "from pypfopt import discrete_allocation" statement to work on my computer, but I am not able to install "pulp". The last test was to create a specific virtual environment for "PyPortfolioOpt", with python 3, I activated it and, within this environment, I installed "pulp" using "conda". When trying the commented import, I get the error "ModuleNotFoundError: No module named 'pulp'". However, when I make a "list" in the environment, I see that "pulp" does appear. What else can I do?. 
Should I install it using pip? I'am using anaconda3 and jupyter notebook, would it affect the installation of these programs?
I will appreciate the help you can give me. Best regards

**Comment by akitxu** [comment] 2020-01-08 20:03
To continue developing a PyPortfolioOpt-based on this project, I need the "from pypfopt import discrete_allocation" sentence to work correctly. This, in turn, needs the "pulp" module. I have done some tests to try to install this module correctly. The last one has been:
- I have created a virtual environment "PyPortfolioOpt" with conda and pyton 3.
- In this environment I installed "PyPortfolioOpt".
- Using "conda", I also installed "pulp" in this environment.
- I checked that "pulp" appears in the list of programs located in this environment.
- When executing the commented import statement, it returnos the error  " ModuleNotFoundError: No module named 'pulp' "
Should I reinstall "pulp" using "pip"?
Could this installation harm the installation of "anaconda3" and "jupyter notebook"?
I will appreciate your suggestions. Best regards

**Comment by schneiderfelipe** [comment] 2020-01-08 20:28
I'm not sure about how that would go with conda. I use pip:

```
➜  ~ pip3 list | grep -i pulp
PuLP (1.6.0)
```

I'm aware there's currently a version 2.0. Can you confirm it's not due to version or letter case (pulp versus PuLP? I'm not even sure if that would change anything with conda/pip)?

**Comment by akitxu** [comment] 2020-01-08 21:32
Thanks Felipe. 
I have pulp version 1.6.8 installed. 
On the other hand, in module "discrete_allocation.py" of this Web, it is where the import is carried out with the "import pulp" statement. I can't do anything to change "pulp" to "PuLP", if this is what you send me to check.

**Comment by akitxu** [comment] 2020-01-08 21:51
Thanks Felipe. Now I understand your comments. If I can uninstall version 1.6.8, I may be encouraged to try installing the 2.0 (PuLP) with pip, just as you tell me.

**Comment by robertmartin8** [comment] 2020-01-09 06:46
@schneiderfelipe 

> Basically, fail silently at import, but throw an error as soon as the functionality is required. What do you think?

I think that makes sense, though I'd be inclined to write it as a try-except:

```python
try:
    import pulp
except ModuleNotFoundError, ImportError:
   raise ImportError("Please install PulP via pip or poetry")
```

Essentially, this pattern lets us change the error message so it's more descriptive to the user. In addition, I will probably not put this in the top-level of the module. Instead I will put it inside the function that requires PulP so it's more self-contained.

On a related note, do you think that I should make `sklearn` optional too? Since it is only called in `risk_models.py`. I'm less certain of this, because I imagine that most users of PyPortfolioOpt will need risk models.

**Comment by schneiderfelipe** [comment] 2020-01-09 13:04
@robertmartin8 
 
> I think that makes sense, though I'd be inclined to write it as a try-except:
> 
> ```python
> try:
>     import pulp
> except ModuleNotFoundError, ImportError:
>    raise ImportError("Please install PulP via pip or poetry")
> ```
> 
> Essentially, this pattern lets us change the error message so it's more descriptive to the user. In addition, I will probably not put this in the top-level of the module. Instead I will put it inside the function that requires PulP so it's more self-contained.

That's good, way better than my suggestion and much cleaner.

> On a related note, do you think that I should make `sklearn` optional too? Since it is only called in `risk_models.py`. I'm less certain of this, because I imagine that most users of PyPortfolioOpt will need risk models.

I'm not sure, this is a bit harder to answer. But I would say yes.

There are simple models available that don't rely on `sklearn`: `sample_cov()`, `semicovariance()`, `exp_cov()`, `shrunk_covariance()`, `ledoit_wolf("single_factor")` and `ledoit_wolf("constant_correlation")`. The ones that do require `sklearn` are `min_cov_determinant()`, `ledoit_wolf("constant_variance")` and `oracle_approximating()`.

**Comment by akitxu** [comment] 2020-01-10 11:18
I have created a new virtual environment and installed using pip pulp.2.0. I continue with the error when importing "pulp".

**Comment by robertmartin8** [comment] 2020-01-11 07:07
@akitxu Please try:

```python
pip install pulp==1.6.10
```

I think I made a mistake in the requirements.txt file, there seems to be another library called `pulp` that does have a 2.0, but it's not the one we want

**Comment by robertmartin8** [comment] 2020-01-11 07:15
@schneiderfelipe 

Actually, if I make the PuLP requirement optional, won't it make my automated tests fail? Because the travis tests spin up a virtual env and install packages from the requirements file 

If this is true, I might have to leave it in as a compulsory dependency for now since I'm not sure how to reconfigure travis for this purpose :(

**Comment by schneiderfelipe** [comment] 2020-01-11 16:32
> @schneiderfelipe
> 
> Actually, if I make the PuLP requirement optional, won't it make my automated tests fail? Because the travis tests spin up a virtual env and install packages from the requirements file
> 
> If this is true, I might have to leave it in as a compulsory dependency for now since I'm not sure how to reconfigure travis for this purpose :(

That's not a problem. As far as I know, pip looks at [`install_requires` within `setup.py`](https://github.com/robertmartin8/PyPortfolioOpt/blob/d0407635713a43ba167f22f12d23d1eedee28384/setup.py#L39). [Travis currently installs what you have in 'requirements.txt`](https://github.com/robertmartin8/PyPortfolioOpt/blob/d0407635713a43ba167f22f12d23d1eedee28384/.travis.yml#L9).

So, if you leave PuLP out of `install_requires`, it won't be installed together with PyPortfolioOpt. But by being in `requirements.txt`, it will be there by the time tests are run by Travis so that you can test still optional features.

I know at least one project that does exactly that. Check out their [`setup.py`](https://github.com/cclib/cclib/blob/92e4e3af0cd0cfc30af2c1e0d8720bf7ce19169a/setup.py#L59) and [`.travis.yml`](https://github.com/cclib/cclib/blob/92e4e3af0cd0cfc30af2c1e0d8720bf7ce19169a/.travis.yml#L38).

**Comment by akitxu** [comment] 2020-01-11 17:46
Yes, every time is the same error

**Comment by robertmartin8** [comment] 2020-01-12 09:11
@schneiderfelipe 

Cheers, let's go with that then!

**Comment by robertmartin8** [comment] 2020-01-12 09:13
@akitxu 

Let's try a few more things:

1. In your virtualenv, open a python shell (in terminal, type `python`). Then run `import pulp` followed by `pulp.LpProblem`. Do you still get the same error?
2. Within your virtualenv, can you please run pip freeze?

Also can you please let me know what python/pip versions you are using, as well as your operating system.

Robert

**Comment by akitxu** [comment] 2020-01-12 10:06
Versions installed in the environment:
pip=19.3.1=py38_0 / pulp=1.6.10=pypi_0 / python=3.8.1=h5fd99cc_1
After opening the Python terminal and running `import pulp` it returns me:
`
(PyPortfolioOpt) C:\Users\akitx>python
Python 3.8.1 (default, Jan  8 2020, 15:55:49) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\PyPortfolioOpt\lib\site-packages\pulp\__init__.py", line 34, in <module>
    from .pulp import *
  File "C:\Anaconda3\envs\PyPortfolioOpt\lib\site-packages\pulp\pulp.py", line 102, in <module>
    from .solvers import *
  File "C:\Anaconda3\envs\PyPortfolioOpt\lib\site-packages\pulp\solvers.py", line 35, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)`
Ejecuto `pulp.LpProblem`

`>>> pulp.LpProblem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pulp' is not defined
>>>`
Within the environment I run `pip freeze` and it returns:

```
(PyPortfolioOpt) C:\Users\akitx>pip freeze
certifi==2019.11.28
PuLP==1.6.10
pyparsing==2.4.6
wincertstore==0.2
```
Thanks for your help

**Comment by akitxu** [comment] 2020-01-12 10:07
My operating system is Windows 10.

**Comment by akitxu** [comment] 2020-01-12 10:11
I will try to see if the same thing happens with "pulp" on another computer with LinuxMint, creating the same environment, cloning and installation of "pulp".

**Comment by robertmartin8** [comment] 2020-01-14 08:51
@akitxu 

Ah, I know what the problem is. `pulp` is currently not compatible with python 3.8, since the library calls the `clock()` function which is deprecated in 3.8. There is a [PR](https://github.com/coin-or/pulp/pull/237) to fix this, but I don't know when it will get merged. 

You have three options:

1. Downgrade from python 3.8 to 3.7
2. Wait till PuLP merges the PR (then upgrade to pulp==2.0)
3. Use the other discrete allocation method, `DiscreteAllocation.greedy_portfolio()`.

I know this is quite annoying – I would like PyPortfolioOpt to be able to support python 3.8 entirely, but currently that is out of my control.

**Closed by robertmartin8** 2020-01-14 08:51 UTC

**Comment by akitxu** [comment] 2020-01-14 22:09
On a Windows 10 OS, I have re-created the Gestion_Resources environment with: pulp 1.6.8, pyportfolioopt 0.5.2.1 and python 3.7.5.I.
I opened with Jupyter "PyPortfolioOpt 0.2.0.ipynb" from HitHub, "Geston_Resources".
When executing module import statements, I still get the error
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2dbdd90821a4> in <module>
      6 from pypfopt.hierarchical_risk_parity import HRPOpt
      7 from pypfopt.value_at_risk import CVAROpt
----> 8 from pypfopt import discrete_allocation

C:\Anaconda3\lib\site-packages\pyportfolioopt-0.5.1-py3.7.egg\pypfopt\discrete_allocation.py in <module>
      6 import numpy as np
      7 import pandas as pd
----> 8 import pulp
      9 
     10 

ModuleNotFoundError: No module named 'pulp'
`
On the other hand, I don't understand what you propose when you write " Use the other discrete allocation method, DiscreteAllocation.greedy_portfolio()".
Thanks

**Comment by akitxu** [comment] 2020-01-14 22:24
" Use the other discrete allocation method, DiscreteAllocation.greedy_portfolio()", ¿It involves using the "Greedy algorithm " [(](https://pyportfolioopt.readthedocs.io/en/latest/Postprocessing.html)?. I think it might be too much for my knowledge.
