### ISSUE TITLE
How to generate efficient frontier with (Big Data) high dimensional input (e.g. 5000 assets)?

### ISSUE THREAD

**Issue by AdamTheDestroyer** [robertmartin8/PyPortfolioOpt#239] opened 2020-12-29 15:13 UTC
Is there meanwhile a  solution for generating efficient frontier with high dimensional input?
Last time i tried it with version 1.2.3.
What i have tried:
Using another solver, because the standard solver cant solve this kind of big problem. 
But it doesnt solve my question, because of very very bad performance or other failures.

I know, the best i could do is posting my  failure message or error code. But in the end its all because of too many inputs.
Thats why i ask if there meanwhile is a solution for my problem. 

Thank you,
greetings Adam

**Comment by phschiele** [comment] 2020-12-29 16:15
@AdamTheDestroyer Would you mind sharing the inputs? I would like to test some different solving methodologies. 

With such a high dimensionality, I am wondering about the number of observations you have for each time series?
One thing that you need to look out for in general is that your optimization results might become suboptimal out of sample if the number of assets approaches or even exceeds the number of observations per asset.

**Comment by robertmartin8** [comment] 2020-12-29 16:16
Hi Adam, I'm closing this issue because it's a continuation of #128. Will respond there.

**Comment by robertmartin8** [comment] 2020-12-29 16:17
(I initially closed it because it's a duplicate of #128, but we can just continue the thread here).

**Closed** 2021-01-02 12:49 UTC
Labels: question
